---
- name: config | pgpass file
  template:
    src: .pgpass.j2
    dest: /var/lib/postgresql/.pgpass
    owner: postgres
    group: postgres
    mode: 0600

- name: config | deploy master pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_config_directory }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify: restart postgresql

- name: config | conf.d config directory
  file:
    path: "{{ postgres_config_directory }}/conf.d"
    owner: postgres
    group: postgres
    state: directory
    mode: 0775

- name: config | deploy configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ postgres_config_directory }}/{{ item }}"
    owner: postgres
    group: postgres
    mode: 0644
  loop:
    - conf.d/01-main.conf
    - conf.d/02-replication.conf
    - conf.d/03-other.conf
    - postgresql.conf
  notify: restart postgresql
