- name: health | check if all slaves are connected to the master
  command: psql -Aqtc "SELECT count(*) FROM pg_stat_replication"
  become: true
  become_user: postgres
  register: slavecount
  vars:
    ansible_ssh_pipelining: false
  until: (slavecount.stdout|string) == ((play_hosts|length - 1)|string)
  retries: 10
  delay: 1
  changed_when: false

- name: health | debug
  debug:
    msg: "Slave count is {{ slavecount.stdout }}"
