---
- name: Prepare Python with SSHd
  hosts: all
  gather_facts: false
  roles:
    - mariancraciun1983.install_python
  tasks:
    - name: prepare | install openssh-server
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
        install_recommends: true
      vars:
        packages:
          - openssh-server
          - sudo
    - name: prepare | enable and start sshd
      systemd:
        name: sshd
        enabled: true
        state: started
